
	/**
	* Generated class via ClassGenerator.xml
	* Creation date: Sun Dec 18 19:38:31 UYST 2016
	* Creator: rlomez
	**/
package pattern01.plugin.components.navigator;

public enum NodeType {
	UNDEFINED,PACKAGE,CLASS,PATTERNINSTANCE_FORM_DATATABLE,PATTERNINSTANCE_FORM_PANEL_DATATABLE,PATTERNINSTANCE_FORM_PANEL_COMMANDBUTTON,PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN_TEXT,PATTERNINSTANCE_FORM_PANELGRID_PANEL_TEXT,PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN,PATTERNINSTANCE_FORM_PANELGRID_PANEL,PATTERNINSTANCE_FORM,PATTERNINSTANCE_FORM_PANELGRID_DATATABLE,PATTERNINSTANCE_FORM_PANELGRID_PANEL_COMMANDBUTTON,PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE,PATTERNINSTANCE,PATTERNINSTANCE_FORM_PANEL_TEXT,PATTERNINSTANCE_FORM_COMMANDBUTTON,PATTERNINSTANCE_FORM_PROPERTY,PATTERNINSTANCE_FORM_PANEL,PATTERNINSTANCE_FORM_PANELGRID,PATTERNINSTANCE_FORM_TEXT,PATTERNINSTANCE_FORM_DATATABLE_COLUMN_TEXT,PATTERNINSTANCE_FORM_PANELGRID_PANEL_PROPERTY,PATTERNINSTANCE_FORM_DATATABLE_COLUMN,PATTERNINSTANCE_FORM_PANELGRID_TEXT,PATTERNINSTANCE_FORM_PANEL_PROPERTY,PATTERNINSTANCE_FORM_MESSAGES,PATTERNINSTANCE_FORM_PANELGRID_COMMANDBUTTON,PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN,PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN,PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN_TEXT,PATTERNINSTANCE_FORM_PANELGRID_PROPERTY,PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN_TEXT;

	public static String toString(NodeType nodetype){
		String nodetypestr = "";
		switch(nodetype){
			case UNDEFINED:
				nodetypestr = "UNDEFINED";
				break;
			case PACKAGE:
				nodetypestr = "PACKAGE";
				break;
			case CLASS:
				nodetypestr = "CLASS";
				break;
			case PATTERNINSTANCE_FORM_DATATABLE:
				nodetypestr = "PATTERNINSTANCE_FORM_DATATABLE";
				break;
			case PATTERNINSTANCE_FORM_PANEL_DATATABLE:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_DATATABLE";
				break;
			case PATTERNINSTANCE_FORM_PANEL_COMMANDBUTTON:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_COMMANDBUTTON";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN_TEXT";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_TEXT";
				break;
			case PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL";
				break;
			case PATTERNINSTANCE_FORM:
				nodetypestr = "PATTERNINSTANCE_FORM";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_DATATABLE:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_DATATABLE";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_COMMANDBUTTON:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_COMMANDBUTTON";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE";
				break;
			case PATTERNINSTANCE:
				nodetypestr = "PATTERNINSTANCE";
				break;
			case PATTERNINSTANCE_FORM_PANEL_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_TEXT";
				break;
			case PATTERNINSTANCE_FORM_COMMANDBUTTON:
				nodetypestr = "PATTERNINSTANCE_FORM_COMMANDBUTTON";
				break;
			case PATTERNINSTANCE_FORM_PROPERTY:
				nodetypestr = "PATTERNINSTANCE_FORM_PROPERTY";
				break;
			case PATTERNINSTANCE_FORM_PANEL:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID";
				break;
			case PATTERNINSTANCE_FORM_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_TEXT";
				break;
			case PATTERNINSTANCE_FORM_DATATABLE_COLUMN_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_DATATABLE_COLUMN_TEXT";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_PROPERTY:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_PROPERTY";
				break;
			case PATTERNINSTANCE_FORM_DATATABLE_COLUMN:
				nodetypestr = "PATTERNINSTANCE_FORM_DATATABLE_COLUMN";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_TEXT";
				break;
			case PATTERNINSTANCE_FORM_PANEL_PROPERTY:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_PROPERTY";
				break;
			case PATTERNINSTANCE_FORM_MESSAGES:
				nodetypestr = "PATTERNINSTANCE_FORM_MESSAGES";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_COMMANDBUTTON:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_COMMANDBUTTON";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PANEL_DATATABLE_COLUMN";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_DATATABLE_COLUMN_TEXT";
				break;
			case PATTERNINSTANCE_FORM_PANELGRID_PROPERTY:
				nodetypestr = "PATTERNINSTANCE_FORM_PANELGRID_PROPERTY";
				break;
			case PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN_TEXT:
				nodetypestr = "PATTERNINSTANCE_FORM_PANEL_DATATABLE_COLUMN_TEXT";
				break;
		}
		return nodetypestr;
	}
}